# Generated by Skyramp v1.3.29 on 2026-06-26 16:31:19.628230983 +0000 UTC m=+323.556821367
# Command: skyramp generate contract rest http://localhost:5080/api/default/dashboards \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_dashboards.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/dashboards POST
def test_dashboards_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    dashboards_POST_request_body = r'''{
        "description": "Traffic patterns and network performance of the infrastructure",
        "title": "Network Traffic Overview"
    }'''

    # Expected Response Body
    expected_dashboards_POST_response_body = r'''{
        "v8": {
            "title": "",
            "description": "",
            "dashboardId": "",
            "owner": "",
            "created": "",
            "version": 0
        },
        "version": 0,
        "updatedAt": 0
    }'''

    # Execute Request
    dashboards_POST_response = client.send_request(
        url=URL,
        path="/api/default/dashboards",
        method="POST",
        body=dashboards_POST_request_body,
        headers=headers,
        query_params={"folder": None}
    )

    # Generated Assertions
    assert dashboards_POST_response.status_code == 200
    assert skyramp.check_schema(dashboards_POST_response, expected_dashboards_POST_response_body)
    assert skyramp.get_response_value(dashboards_POST_response, "v8.title") == "Network Traffic Overview"
    assert skyramp.get_response_value(dashboards_POST_response, "v8.description") == "Traffic patterns and network performance of the infrastructure"
    assert skyramp.get_response_value(dashboards_POST_response, "v8.dashboardId") is not None
    assert skyramp.get_response_value(dashboards_POST_response, "v8.owner") is not None
    created_val = skyramp.get_response_value(dashboards_POST_response, "v8.created")
    assert created_val is not None and len(created_val) >= 10 and created_val[4] == "-"
    assert skyramp.get_response_value(dashboards_POST_response, "version") >= 0
    assert skyramp.get_response_value(dashboards_POST_response, "updatedAt") >= 0


if __name__ == "__main__":
    test_dashboards_post()
