# Generated by Skyramp v1.3.29 on 2026-06-25 00:09:38.970015509 +0000 UTC m=+231.795904348
# Command: skyramp generate contract rest http://localhost:5080/api/default/streams \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_streams_has_data_numeric_1_400.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params has_data=1 \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/streams GET
def test_streams_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_streams_GET_response_body = r'''{"code": 400, "message": "'has_data' query param must be 'true' or 'false'"}'''

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL,
        path="/api/default/streams",
        method="GET",
        headers=headers,
        query_params={"has_data": "1"}
    )

    # Generated Assertions
    assert streams_GET_response.status_code == 400
    assert skyramp.check_schema(streams_GET_response, expected_streams_GET_response_body)
    assert skyramp.get_response_value(streams_GET_response, "code") == 400
    assert skyramp.get_response_value(streams_GET_response, "message") == "'has_data' query param must be 'true' or 'false'"


if __name__ == "__main__":
    test_streams_get()
