# Generated by Skyramp v1.3.29 on 2026-06-24 23:53:44.236174111 +0000 UTC m=+259.297403391
# Command: skyramp generate contract rest http://localhost:5080/api/default/streams \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_streams_no_param_backcompat.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/streams GET
def test_streams_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_streams_GET_response_body = r'''{
        "list": [
            {
                "name": "string",
                "schema": [
                    {
                        "name": "string",
                        "type": "string"
                    }
                ],
                "settings": {
                    "approx_partition": false,
                    "bloom_filter_fields": [
                        "string"
                    ],
                    "cross_links": [
                        {
                            "name": "string",
                            "url": "string"
                        }
                    ],
                    "data_retention": 0,
                    "defined_schema_fields": [
                        "string"
                    ],
                    "distinct_value_fields": [
                        {
                            "added_ts": 0,
                            "name": "string"
                        }
                    ],
                    "enable_distinct_fields": false,
                    "enable_log_patterns_extraction": false,
                    "extended_retention_days": [
                        {
                            "end": 0,
                            "start": 0
                        }
                    ],
                    "flatten_level": 0,
                    "full_text_search_keys": [
                        "string"
                    ],
                    "index_all_values": false,
                    "index_fields": [
                        "string"
                    ],
                    "index_fields_updated_at": {
                        "key": 0
                    },
                    "index_original_data": false,
                    "index_updated_at": 0,
                    "is_llm_stream": false,
                    "max_query_range": 0,
                    "partition_keys": [
                        {
                            "field": "string"
                        }
                    ],
                    "storage_type": "normal",
                    "store_original_data": false
                },
                "stats": {
                    "compressed_size": 0,
                    "created_at": 0,
                    "doc_num": 0,
                    "doc_time_max": 0,
                    "doc_time_min": 0,
                    "file_num": 0,
                    "index_size": 0,
                    "storage_size": 0
                },
                "storage_type": "string",
                "stream_type": "logs",
                "total_fields": 0
            }
        ],
        "total": 0
    }'''

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL,
        path="/api/default/streams",
        method="GET",
        headers=headers,
        query_params={
            "keyword": None,
            "limit": None,
            "offset": None,
            "sort": None,
            "type": None
        }
    )

    # Generated Assertions
    assert streams_GET_response.status_code == 200
    assert skyramp.check_schema(streams_GET_response, expected_streams_GET_response_body)
    assert skyramp.get_response_value(streams_GET_response, "list.0.name") is not None
    assert skyramp.get_response_value(streams_GET_response, "list.0.stats") is not None
    assert skyramp.get_response_value(streams_GET_response, "total") is not None
    assert skyramp.get_response_value(streams_GET_response, "list.0.stream_type") is not None
    assert skyramp.get_response_value(streams_GET_response, "list.0.stats.doc_num") is not None


if __name__ == "__main__":
    test_streams_get()
