# Generated by Skyramp v1.3.29 on 2026-06-26 16:31:16.964050186 +0000 UTC m=+320.892640550
# Command: skyramp generate contract rest http://localhost:5080/api/default/dashboards \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_dashboards.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/dashboards GET
def test_dashboards_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_dashboards_GET_response_body = r'''{
        "dashboards": [
            {
                "created": "2026-06-26T16:31:16Z",
                "dashboard_id": "string",
                "description": "string",
                "folder_id": "string",
                "folder_name": "string",
                "hash": "string",
                "owner": "string",
                "role": "string",
                "title": "string",
                "updatedAt": 0,
                "version": 0
            }
        ]
    }'''

    # Execute Request
    dashboards_GET_response = client.send_request(
        url=URL,
        path="/api/default/dashboards",
        method="GET",
        headers=headers,
        query_params={
            "folder": None,
            "pageSize": None,
            "title": None
        }
    )

    # Generated Assertions
    assert dashboards_GET_response.status_code == 200
    assert skyramp.get_response_value(dashboards_GET_response, "dashboards") is not None


if __name__ == "__main__":
    test_dashboards_get()
