# Generated by Skyramp v1.3.29 on 2026-06-26 16:31:13.673120351 +0000 UTC m=+317.601710735
# Command: skyramp generate contract rest http://localhost:5080/api/organizations \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_organizations.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/organizations GET
def test_organizations_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_organizations_GET_response_body = r'''{
        "data": [
            {
                "UserObj": {
                    "email": "string",
                    "first_name": "string",
                    "last_name": "string"
                },
                "id": 0,
                "identifier": "string",
                "ingest_threshold": 0,
                "name": "string",
                "search_threshold": 0,
                "type": "string",
                "user_email": "string"
            }
        ]
    }'''

    # Execute Request
    organizations_GET_response = client.send_request(
        url=URL,
        path="/api/organizations",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert organizations_GET_response.status_code == 200
    assert skyramp.check_schema(organizations_GET_response, expected_organizations_GET_response_body)
    assert skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.email") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.first_name") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.last_name") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.id") > 0
    assert skyramp.get_response_value(organizations_GET_response, "data.0.ingest_threshold") >= 0
    assert skyramp.get_response_value(organizations_GET_response, "data.0.search_threshold") >= 0
    user_email_val = skyramp.get_response_value(organizations_GET_response, "data.0.user_email")
    assert user_email_val is not None and "@" in user_email_val
    obj_email_val = skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.email")
    assert obj_email_val is not None and "@" in obj_email_val


if __name__ == "__main__":
    test_organizations_get()
