# Generated by Skyramp v1.3.29 on 2026-06-25 00:09:58.430919497 +0000 UTC m=+251.256808336
# Command: skyramp generate contract rest http://localhost:5080/api/default/streams \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_streams_no_auth_401.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/streams GET
def test_streams_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # No auth header — intentionally unauthenticated to verify 401 response
    headers = {}

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL,
        path="/api/default/streams",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert streams_GET_response.status_code == 401
    assert skyramp.get_response_value(streams_GET_response, "code") == 401
    assert skyramp.get_response_value(streams_GET_response, "message") == "Unauthorized Access"


if __name__ == "__main__":
    test_streams_get()
