# Generated by Skyramp v1.3.28 on 2026-06-24 23:26:45.817290903 +0000 UTC m=+205.933473998
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output dashboard_crud_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve-testb/openobserve-testb/tests/scenario_dashboard-crud-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    dashboards_POST_request_body = r'''{
        "description": "Dashboard created by Skyramp Testbot",
        "tabs": [],
        "title": "Testbot Dashboard"
    }'''
    
    # Execute Request
    dashboards_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/dashboards",
        method="POST",
        body=dashboards_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert dashboards_POST_response.status_code == 200
    assert skyramp.get_response_value(dashboards_POST_response, "v8.title") == "Testbot Dashboard"
    assert skyramp.get_response_value(dashboards_POST_response, "v8.dashboardId") is not None
    dashboards = skyramp.get_response_value(dashboards_POST_response, "v8.dashboardId")

    # Execute Request
    dashboards_dashboards_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/default/dashboards/{dashboards}",
        method="GET",
        headers=headers,
        path_params={"dashboards": dashboards}
    )
    # Generated Assertions
    assert dashboards_dashboards_GET_response.status_code == 200
    assert skyramp.get_response_value(dashboards_dashboards_GET_response, "v8.title") == "Testbot Dashboard"
    assert skyramp.get_response_value(dashboards_dashboards_GET_response, "v8.dashboardId") is not None

    # Execute Request
    dashboards_dashboards_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/default/dashboards/{dashboards}",
        method="DELETE",
        headers=headers,
        path_params={"dashboards": dashboards}
    )
    # Generated Assertions
    assert dashboards_dashboards_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
