# Generated by Skyramp v1.3.17 on 2026-06-29 18:48:04.787447962 +0000 UTC m=+227.508334324
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output node_list_removed_404_integration_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /_work/rachzucco/openobserve-testb/openobserve-testb/tests/scenario_node-list-removed-404.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    list_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/_meta/node/list",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert list_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
