# Generated by Skyramp v1.3.17 on 2026-06-29 18:48:06.904525769 +0000 UTC m=+229.625412123
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output org_endpoints_regression_integration_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /_work/rachzucco/openobserve-testb/openobserve-testb/tests/scenario_org-endpoints-regression.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    api = "default"

    # Execute Request
    organizations_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/organizations",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert organizations_GET_response.status_code == 200
    assert skyramp.get_response_value(organizations_GET_response, "data.0.identifier") is not None

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/summary",
        method="GET",
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert summary_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
