# Generated by Skyramp v1.3.17 on 2026-06-29 18:47:54.150134015 +0000 UTC m=+216.871020363
# Command: skyramp generate contract rest http://localhost:5080/api/organizations \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output organizations_contract_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/organizations GET
def test_organizations_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_organizations_GET_response_body = r'''{
        "data": [
            {
                "UserObj": {
                    "email": "root@example.com",
                    "first_name": "Admin",
                    "last_name": "User"
                },
                "id": 1,
                "identifier": "default",
                "ingest_threshold": 0,
                "name": "default",
                "plan": 0,
                "search_threshold": 0,
                "type": "default",
                "user_email": "root@example.com"
            }
        ]
    }'''

    # Execute Request
    organizations_GET_response = client.send_request(
        url=URL,
        path="/api/organizations",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert organizations_GET_response.status_code == 200
    assert skyramp.check_schema(organizations_GET_response, expected_organizations_GET_response_body)
    assert skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.email") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.first_name") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.UserObj.last_name") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.identifier") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.name") is not None
    assert skyramp.get_response_value(organizations_GET_response, "data.0.user_email") is not None


if __name__ == "__main__":
    test_organizations_get()
