# Generated by Skyramp v1.3.17 on 2026-06-29 20:33:23.866632191 +0000 UTC m=+189.000527591
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output streams_has_data_invalid_integration_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /_work/rachzucco/openobserve-testb/openobserve-testb/tests/scenario_streams-has-data-invalid.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/default/streams",
        method="GET",
        headers=headers,
        query_params={"has_data": ["invalid"]}
    )
    # Generated Assertions
    assert streams_GET_response.status_code == 400


if __name__ == "__main__":
    test_integration()
