# Generated by Skyramp v1.3.29 on 2026-06-28 00:48:32.661605277 +0000 UTC m=+398.222197332
# Command: skyramp generate contract rest http://localhost:5080/api/{org_id}/streams/_stats_summary \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output streams_stats_summary_contract_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--path-params org_id=default \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/{org_id}/streams/_stats_summary GET
def test__stats_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    org_id = "default"

    # Execute Request
    _stats_summary_GET_response = client.send_request(
        url=URL,
        path="/api/{org_id}/streams/_stats_summary",
        method="GET",
        headers=headers,
        path_params={"org_id": org_id}
    )

    # Generated Assertions
    assert _stats_summary_GET_response.status_code == 200
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.total") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.logs") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.metrics") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.traces") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.logs") + skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.metrics") + skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.traces") <= skyramp.get_response_value(_stats_summary_GET_response, "json.total")


if __name__ == "__main__":
    test__stats_summary_get()
