# Generated by Skyramp v1.3.29 on 2026-06-24 23:53:53.167570584 +0000 UTC m=+268.228799864
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output streams_has_data_filter_integration_test.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve-testb/openobserve-testb/tests/scenario_streams_has_data_filter.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    default = "test_has_data_filter"

    # Request Body
    _json_POST_request_body = r'''[
        {
            "level": "info",
            "message": "test log entry for has_data filter"
        }
    ]'''
    
    # Execute Request
    _json_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/{default}/_json",
        method="POST",
        body=_json_POST_request_body,
        headers=headers,
        path_params={"default": default}
    )
    # Generated Assertions
    assert _json_POST_response.status_code == 200
    assert skyramp.get_response_value(_json_POST_response, "code") == 200

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/default/streams",
        method="GET",
        headers=headers,
        query_params={"has_data": ["true"]}
    )
    # Generated Assertions
    assert streams_GET_response.status_code == 200
    assert skyramp.get_response_value(streams_GET_response, "list") is not None
    assert skyramp.get_response_value(streams_GET_response, "total") is not None


if __name__ == "__main__":
    test_integration()
