# Generated by Skyramp v1.3.17 on 2026-06-29 20:33:21.658660918 +0000 UTC m=+186.792556320
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output streams_has_data_filter_integration_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /_work/rachzucco/openobserve-testb/openobserve-testb/tests/scenario_streams-has-data-filter.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    api = "default"
    has_data = "false"

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/streams",
        method="GET",
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert streams_GET_response.status_code == 200
    assert skyramp.get_response_value(streams_GET_response, "total") is not None
    assert skyramp.get_response_value(streams_GET_response, "total") >= 0
    assert skyramp.get_response_value(streams_GET_response, "list") is not None

    # Execute Request
    streams_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/streams",
        method="GET",
        headers=headers,
        path_params={"api": api},
        query_params={"has_data": ["true"]}
    )
    # Generated Assertions
    assert streams_GET_1_response.status_code == 200
    assert skyramp.get_response_value(streams_GET_1_response, "total") is not None
    assert skyramp.get_response_value(streams_GET_1_response, "total") >= 0
    assert skyramp.get_response_value(streams_GET_1_response, "total") <= skyramp.get_response_value(streams_GET_response, "total")

    # Execute Request
    streams_GET_2_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/streams",
        method="GET",
        headers=headers,
        path_params={"api": api},
        query_params={"has_data": ["false"]}
    )
    # Generated Assertions
    assert streams_GET_2_response.status_code == 200
    assert skyramp.get_response_value(streams_GET_2_response, "total") is not None
    assert skyramp.get_response_value(streams_GET_2_response, "total") == skyramp.get_response_value(streams_GET_response, "total")


if __name__ == "__main__":
    test_integration()
