# Generated by Skyramp v1.3.17 on 2026-06-29 20:33:25.668874074 +0000 UTC m=+190.802769480
# Command: skyramp generate contract rest http://localhost:5080/api/default/streams \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output streams_list_contract_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/streams GET
def test_streams_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL,
        path="/api/default/streams",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(streams_GET_response, "20x")
    assert skyramp.get_response_value(streams_GET_response, "total") is not None
    assert skyramp.get_response_value(streams_GET_response, "total") >= 0
    assert skyramp.get_response_value(streams_GET_response, "list") is not None


if __name__ == "__main__":
    test_streams_get()
