# Generated by Skyramp v1.3.17 on 2026-06-29 19:41:22.204667065 +0000 UTC m=+156.477101677
# Command: skyramp generate fuzz rest http://localhost:5080/api/default/streams \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output streams_list_fuzz_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# fuzz test for /api/default/streams GET
def test_streams_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL,
        path="/api/default/streams",
        method="GET",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_streams_get()
