# Generated by Skyramp v1.3.28 on 2026-06-24 23:26:43.897978217 +0000 UTC m=+204.014161321
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output stream_ingest_and_search_integration_test.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve-testb/openobserve-testb/tests/scenario_stream-ingest-and-search.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    default = "teststream"

    # Request Body
    _json_POST_request_body = r'''[
        {
            "level": "info",
            "message": "testbot-smoke-test",
            "service": "testbot"
        }
    ]'''
    
    # Execute Request
    _json_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/{default}/_json",
        method="POST",
        body=_json_POST_request_body,
        headers=headers,
        path_params={"default": default}
    )
    # Generated Assertions
    assert _json_POST_response.status_code == 200
    assert skyramp.get_response_value(_json_POST_response, "status.0.name") == "teststream"
    assert skyramp.get_response_value(_json_POST_response, "status.0.successful") == 1
    assert skyramp.get_response_value(_json_POST_response, "status.0.failed") == 0
    assert skyramp.get_response_value(_json_POST_response, "status.1") is None

    # Request Body
    _search_end_time = int(time.time() * 1_000_000)
    _search_start_time = _search_end_time - 3600_000_000
    _search_POST_request_body = f'''{{"query": {{"end_time": {_search_end_time}, "from": 0, "size": 10, "sql": "SELECT * FROM teststream LIMIT 10", "start_time": {_search_start_time}}}}}'''
    
    # Execute Request
    _search_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/_search",
        method="POST",
        body=_search_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert _search_POST_response.status_code == 200
    assert skyramp.get_response_value(_search_POST_response, "took") >= 0


if __name__ == "__main__":
    test_integration()
