# Generated by Skyramp v1.3.29 on 2026-06-28 00:47:49.128240131 +0000 UTC m=+354.688832204
# Command: skyramp generate contract rest http://localhost:5080/api/{org_id}/streams/_stats_summary \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output streams_stats_summary_unauth_contract_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--path-params org_id=default \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/{org_id}/streams/_stats_summary GET
def test__stats_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # No authentication header — intentionally unauthenticated to verify 401 enforcement
    headers = {}

    # Declaration of variables
    org_id = "default"

    # Execute Request
    _stats_summary_GET_response = client.send_request(
        url=URL,
        path="/api/{org_id}/streams/_stats_summary",
        method="GET",
        headers=headers,
        path_params={"org_id": org_id}
    )

    # Generated Assertions
    assert _stats_summary_GET_response.status_code == 401


if __name__ == "__main__":
    test__stats_summary_get()
