# Generated by Skyramp v1.3.17 on 2026-06-29 19:41:15.467435302 +0000 UTC m=+149.739869958
# Command: skyramp generate contract rest http://localhost:5080/api/default/streams \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output streams_list_contract_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"list":[{"name":"default","stream_type":"logs","settings":{"max_query_range":0,"store_original_data":false,"bloom_filter_fields":[],"data_retention":0},"schema":[],"stats":{"file_num":0,"doc_num":0,"storage_size":0,"compressed_size":0,"index_size":0},"retention_period_days":null}]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/streams GET
def test_streams_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_streams_GET_response_body = r'''{
        "list": [
            {
                "name": "default",
                "retention_period_days": null,
                "schema": [],
                "settings": {
                    "bloom_filter_fields": [],
                    "data_retention": 0,
                    "max_query_range": 0,
                    "store_original_data": false
                },
                "stats": {
                    "compressed_size": 0,
                    "doc_num": 0,
                    "file_num": 0,
                    "index_size": 0,
                    "storage_size": 0
                },
                "stream_type": "logs"
            }
        ]
    }'''

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL,
        path="/api/default/streams",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(streams_GET_response, "20x")
    assert skyramp.check_schema(streams_GET_response, expected_streams_GET_response_body)
    assert skyramp.get_response_value(streams_GET_response, "list.0.name") is not None
    assert skyramp.get_response_value(streams_GET_response, "list.0.stream_type") is not None
    assert skyramp.get_response_value(streams_GET_response, "list.0.schema") is not None


if __name__ == "__main__":
    test_streams_get()
