# Generated by Skyramp v1.3.29 on 2026-06-28 00:48:05.383844883 +0000 UTC m=+370.944436974
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output streams_stats_summary_consistency_integration_test.py \
# 		--output-dir /_work/rachzucco/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /_work/rachzucco/openobserve-testb/openobserve-testb/tests/scenario_streams-stats-summary-consistency.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    api = "default"

    # Execute Request
    streams_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/streams",
        method="GET",
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert streams_GET_response.status_code == 200
    assert skyramp.get_response_value(streams_GET_response, "json.list") is not None

    # Execute Request
    _stats_summary_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/streams/_stats_summary",
        method="GET",
        headers=headers,
        path_params={"api": api}
    )
    # Generated Assertions
    assert _stats_summary_GET_response.status_code == 200
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.total") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.logs") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.metrics") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.by_type.traces") >= 0
    assert skyramp.get_response_value(_stats_summary_GET_response, "json.total") == len(skyramp.get_response_value(streams_GET_response, "json.list"))


if __name__ == "__main__":
    test_integration()
