# Generated by Skyramp v1.3.28 on 2026-06-24 23:28:31.228868524 +0000 UTC m=+311.345051618
# Command: skyramp generate contract rest http://localhost:5080/api/default/users \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output users_list_contract_test.py \
# 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/users GET
def test_users_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_users_GET_response_body = r'''{}'''

    # Execute Request
    users_GET_response = client.send_request(
        url=URL,
        path="/api/default/users",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert users_GET_response.status_code == 200
    assert skyramp.check_schema(users_GET_response, expected_users_GET_response_body)
    assert skyramp.get_response_value(users_GET_response, "data.0.email") is not None


if __name__ == "__main__":
    test_users_get()
