// Generated by Skyramp v1.3.29 on 2026-06-26 21:23:44.308035327 +0000 UTC m=+702.249210240
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output app_data_theme_persist.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve-testb/openobserve-testb/.skyramp/app_data_theme_persist_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(109000);

    const errors: Error[] = [];
    page.on('pageerror', error => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/web");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await expect(page).toHaveURL(/\/web\//);

    await page.locator("body").click({ position: {"x": 1141, "y": 20} });
    await page.waitForTimeout(2000);
    await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");

    await page.locator("[data-test=\"navbar-theme-toggle-btn\"]").click();
    await page.waitForTimeout(2000);
    await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
    await expect(page.getByRole("link", { name: "Logs - Current page" })).toContainText("Logs");

    expect(errors).toHaveLength(0);
});
