// Generated by Skyramp v1.3.29 on 2026-06-26 16:31:49.531346052 +0000 UTC m=+378.305544942
// Command: skyramp generate contract rest http://localhost:5080/api/default/streams \
// 		--api-schema http://localhost:5080/api-doc/openapi.json \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_streams.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

// contract test for /api/default/streams GET
test('testStreamsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedStreamsGetResponseBody: string = `{
        "list": [
            {
                "name": "string",
                "schema": [
                    {
                        "name": "string",
                        "type": "string"
                    }
                ],
                "settings": {
                    "approx_partition": false,
                    "bloom_filter_fields": [
                        "string"
                    ],
                    "cross_links": [
                        {
                            "name": "string",
                            "url": "string"
                        }
                    ],
                    "data_retention": 0,
                    "defined_schema_fields": [
                        "string"
                    ],
                    "distinct_value_fields": [
                        {
                            "added_ts": 0,
                            "name": "string"
                        }
                    ],
                    "enable_distinct_fields": false,
                    "enable_log_patterns_extraction": false,
                    "extended_retention_days": [
                        {
                            "end": 0,
                            "start": 0
                        }
                    ],
                    "flatten_level": 0,
                    "full_text_search_keys": [
                        "string"
                    ],
                    "index_all_values": false,
                    "index_fields": [
                        "string"
                    ],
                    "index_fields_updated_at": {
                        "key": 0
                    },
                    "index_original_data": false,
                    "index_updated_at": 0,
                    "is_llm_stream": false,
                    "max_query_range": 0,
                    "partition_keys": [
                        {
                            "field": "string"
                        }
                    ],
                    "storage_type": "normal",
                    "store_original_data": false
                },
                "stats": {
                    "compressed_size": 0,
                    "created_at": 0,
                    "doc_num": 0,
                    "doc_time_max": 0,
                    "doc_time_min": 0,
                    "file_num": 0,
                    "index_size": 0,
                    "storage_size": 0
                },
                "storage_type": "string",
                "stream_type": "logs",
                "total_fields": 0
            }
        ],
        "total": 0
    }`;

    // Execute Request
    const streamsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/default/streams",
        method: "GET",
        headers: headers,
        queryParams: {
            "keyword": null,
            "limit": null,
            "offset": null,
            "sort": null,
            "type": null
        }
    });

    // Generated Assertions
    expect(streamsGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(streamsGetResponse, expectedStreamsGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(streamsGetResponse, "list.0.name"), 'value').not.toBeNull();
    expect(getResponseValue(streamsGetResponse, "list.0.stream_type"), 'value').not.toBeNull();
    expect(getResponseValue(streamsGetResponse, "total"), 'total').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(streamsGetResponse, "list.0.stream_type"), 'stream_type').toBe("logs");
    expect(getResponseValue(streamsGetResponse, "list.0.settings.storage_type"), 'storage_type').toBe("normal");
});
