// Generated by Skyramp v1.3.29 on 2026-06-28 01:09:58.836038133 +0000 UTC m=+597.520494151
// Command: skyramp generate contract rest http://localhost:5080/api/default/streams/{stream_name}/settings \
// 		--api-schema http://localhost:5080/api-doc/openapi.json \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output contract_put_streams_settings.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--parent-request-data stream_name={"fields":[{"name":"log_level","type":"Utf8"}],"settings":{}} \
// 		--parent-status-code stream_name=200 \
// 		--provider \
// 		--request-data {"full_text_search_keys":[],"index_fields":[],"bloom_filter_fields":[],"distinct_value_fields":[],"data_retention":7,"max_query_range":0,"store_original_data":true,"approx_partition":false} \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.beforeAll(async () => {
    const setupClient = new SkyrampClient();
    const setupHeaders: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        setupHeaders["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }
    await setupClient.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "POST",
        body: JSON.stringify({"fields":[{"name":"log_level","type":"Utf8"}],"settings":{}}),
        headers: setupHeaders,
        pathParams: {"stream_name": "skyramp_settings_put_test"}
    });
});

test.afterAll(async () => {
    const cleanupClient = new SkyrampClient();
    const cleanupHeaders: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        cleanupHeaders["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }
    await cleanupClient.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "DELETE",
        headers: cleanupHeaders,
        pathParams: {"stream_name": "skyramp_settings_put_test"}
    });
});

// contract test for /api/default/streams/{stream_name}/settings PUT
test('testSettingsPut', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const stream_name = "skyramp_settings_put_test";

    // Request Body
    const settingsPutRequestBody: string = `{
        "approx_partition": false,
        "bloom_filter_fields": [],
        "data_retention": 7,
        "distinct_value_fields": [],
        "full_text_search_keys": [],
        "index_fields": [],
        "max_query_range": 0,
        "store_original_data": true
    }`;

    // Expected Response Body
    const expectedSettingsPutResponseBody: string = `{}`;

    // Execute Request
    const settingsPutResponse = await client.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}/settings",
        method: "PUT",
        body: settingsPutRequestBody,
        headers: headers,
        pathParams: {"stream_name": stream_name}
    });

    // Generated Assertions
    expect(settingsPutResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(settingsPutResponse, expectedSettingsPutResponseBody), 'schema').toBeTruthy();
    expect(getValue(settingsPutResponse, "error"), 'no error field').toBeNull();
});
