// Generated by Skyramp v1.3.29 on 2026-06-28 00:15:55.236785546 +0000 UTC m=+392.231406996
// Command: skyramp generate contract rest http://localhost:5080/api/default/streams/{stream_name} \
// 		--api-schema http://localhost:5080/api-doc/openapi.json \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--method DELETE \
// 		--output contract_delete_stream_success.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--parent-request-data stream_name={"fields":[{"name":"log_level","type":"keyword"}],"settings":{}} \
// 		--parent-status-code stream_name=200 \
// 		--provider \
// 		--response-data {"code":200,"message":"stream deleted"} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.beforeAll(async () => {
    const setupClient = new SkyrampClient();
    const setupHeaders: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        setupHeaders["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }
    await setupClient.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "POST",
        body: JSON.stringify({"fields":[{"name":"log_level","type":"Utf8"}],"settings":{}}),
        headers: setupHeaders,
        pathParams: {"stream_name": "skyramp-del-success-test"}
    });
});

// contract test for /api/default/streams/{stream_name} DELETE
test('testStreamsStreamNameDelete', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const stream_name = "skyramp-del-success-test";

    // Expected Response Body
    const expectedStreamsStreamNameDeleteResponseBody: string = `{
        "code": 200,
        "message": "stream deleted"
    }`;

    // Execute Request
    const streamsStreamNameDeleteResponse = await client.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "DELETE",
        headers: headers,
        pathParams: {"stream_name": stream_name},
        queryParams: {
            "delete_all": null,
            "type": null
        }
    });

    // Generated Assertions
    expect(streamsStreamNameDeleteResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(streamsStreamNameDeleteResponse, expectedStreamsStreamNameDeleteResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(streamsStreamNameDeleteResponse, "code"), 'value').not.toBeNull();
    expect(getResponseValue(streamsStreamNameDeleteResponse, "message"), 'value').not.toBeNull();
    expect(getResponseValue(streamsStreamNameDeleteResponse, "code"), 'code').toBe(200);
    expect(getResponseValue(streamsStreamNameDeleteResponse, "message"), 'message').toBe("stream deleted");
});
