// Generated by Skyramp v1.3.29 on 2026-06-28 01:10:02.258342415 +0000 UTC m=+600.942798443
// Command: skyramp generate contract rest http://localhost:5080/api/default/streams/{stream_name}/schema \
// 		--api-schema http://localhost:5080/api-doc/openapi.json \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_streams_schema.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--parent-request-data stream_name={"fields":[{"name":"log_level","type":"Utf8"}],"settings":{}} \
// 		--parent-status-code stream_name=200 \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test.beforeAll(async () => {
    const setupClient = new SkyrampClient();
    const setupHeaders: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        setupHeaders["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }
    await setupClient.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "POST",
        body: JSON.stringify({"fields":[{"name":"log_level","type":"Utf8"}],"settings":{}}),
        headers: setupHeaders,
        pathParams: {"stream_name": "skyramp_schema_get_test"}
    });
});

test.afterAll(async () => {
    const cleanupClient = new SkyrampClient();
    const cleanupHeaders: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        cleanupHeaders["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }
    await cleanupClient.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "DELETE",
        headers: cleanupHeaders,
        pathParams: {"stream_name": "skyramp_schema_get_test"}
    });
});

// contract test for /api/default/streams/{stream_name}/schema GET
test('testSchemaGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const stream_name = "skyramp_schema_get_test";

    // Expected Response Body
    const expectedSchemaGetResponseBody: string = `{}`;

    // Execute Request
    const schemaGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}/schema",
        method: "GET",
        headers: headers,
        pathParams: {"stream_name": stream_name},
        queryParams: {
            "keyword": null,
            "limit": null,
            "offset": null,
            "type": null
        }
    });

    // Generated Assertions
    expect(schemaGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(schemaGetResponse, expectedSchemaGetResponseBody), 'schema').toBeTruthy();
    expect(getValue(schemaGetResponse, "error"), 'no error field').toBeNull();
});
