// Generated by Skyramp v1.3.29 on 2026-06-28 00:15:58.549397374 +0000 UTC m=+395.544018824
// Command: skyramp generate contract rest http://localhost:5080/api/default/streams/{stream_name} \
// 		--api-schema http://localhost:5080/api-doc/openapi.json \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_post_streams.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--path-params stream_name=skyramp-contract-post-test \
// 		--provider \
// 		--request-data {"fields":[{"name":"log_level","type":"keyword"}],"settings":{}} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

// contract test for /api/default/streams/{stream_name} POST
test('testStreamsStreamNamePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const stream_name = "skyramp-contract-post-test";

    // Request Body
    const streamsStreamNamePostRequestBody: string = `{
        "fields": [
            {
                "name": "log_level",
                "type": "Utf8"
            }
        ],
        "settings": {}
    }`;

    // Expected Response Body
    const expectedStreamsStreamNamePostResponseBody: string = `{}`;

    // Execute Request
    const streamsStreamNamePostResponse = await client.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "POST",
        body: streamsStreamNamePostRequestBody,
        headers: headers,
        pathParams: {"stream_name": stream_name},
        queryParams: {"type": null}
    });

    // Generated Assertions
    expect(streamsStreamNamePostResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(streamsStreamNamePostResponse, expectedStreamsStreamNamePostResponseBody), 'schema').toBeTruthy();
    expect(getValue(streamsStreamNamePostResponse, "error"), 'no error field').toBeNull();
});
