// Generated by Skyramp v1.3.29 on 2026-06-26 16:34:53.063093818 +0000 UTC m=+561.837292698
// Command: skyramp generate contract rest http://localhost:5080/api/default/streams/{stream_name} \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--method DELETE \
// 		--output contract_delete_stream.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--path-params stream_name=skyramp-contract-del-test \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkStatusCode, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

// contract test for /api/default/streams/{stream_name} DELETE
test('testStreamsStreamNameDelete', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const stream_name = "skyramp-contract-del-test";

    // Execute Request
    const streamsStreamNameDeleteResponse = await client.sendRequest({
        url: URL,
        path: "/api/default/streams/{stream_name}",
        method: "DELETE",
        headers: headers,
        pathParams: {"stream_name": stream_name}
    });

    // Generated Assertions
    expect(streamsStreamNameDeleteResponse.statusCode, 'status code').toBe(404);
});
