// Generated by Skyramp v1.3.29 on 2026-06-25 15:31:11.150643472 +0000 UTC m=+665.415996565
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output data_theme_on_load.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve-testb/openobserve-testb/.skyramp/data_theme_on_load_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(322000);
    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/web");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveURL(/\/web\//);
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    expect(errors).toHaveLength(0);
});
