// Generated by Skyramp v1.3.29 on 2026-06-25 15:30:29.062661765 +0000 UTC m=+639.855115659
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output delete_stream_esc_ui_test.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve-testb/openobserve-testb/.skyramp/delete_stream_esc_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(94000);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5080/web/streams?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"log-stream-delete-btn\"]").click();
    await page.keyboard.press("Escape");
    await expect(page.getByText("Stream(s)")).toHaveText("1 Stream(s)");
    expect(errors).toHaveLength(0);
});
