// Generated by Skyramp v1.3.29 on 2026-06-26 21:20:19.538197443 +0000 UTC m=+508.016337101
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output logstream_delete_esc.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve-testb/openobserve-testb/.skyramp/logstream_delete_esc_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(82000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/streams?org_identifier=default");
    await page.locator("[data-test=\"log-stream-delete-btn\"]").click();
    await expect(page.locator('[data-test="o-dialog-secondary-btn"]')).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(page.locator('[data-test="o-dialog-secondary-btn"]')).not.toBeVisible();
    await expect(page.getByText("Stream(s)")).toContainText("1 Stream(s)");
    expect(pageErrors).toHaveLength(0);
});
