// Generated by Skyramp v1.3.29 on 2026-06-28 00:16:09.775968893 +0000 UTC m=+406.770590343
// Command: skyramp generate integration rest \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--output streams_settings_delete_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/openobserve-testb/openobserve-testb/web/tests/scenario_streams-settings-delete-lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let streams = "skyramp-settings-test-1";

    // Request Body
    const streamsStreamsPostRequestBody = `{
            "fields": [
                {
                    "name": "log_level",
                    "type": "Utf8"
                }
            ],
            "settings": {}
        }`
    
    // Execute Request
    let streamsStreamsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams/{streams}",
        method:"POST",
        body:streamsStreamsPostRequestBody,
        headers:headers,
        pathParams:{"streams": streams}
    });

    // Generated Assertions
    expect(streamsStreamsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(streamsStreamsPostResponse, "code"), 'code').toBe(200);

    // Execute Request
    let streamsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(streamsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(streamsGetResponse, "total"), 'total').toBeGreaterThanOrEqual(1);

    // Execute Request
    let streamsStreamsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams/{streams}",
        method:"DELETE",
        headers:headers,
        pathParams:{"streams": streams}
    });

    // Generated Assertions
    expect(streamsStreamsDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getValue(streamsStreamsDeleteResponse, "code"), 'delete code').toBe(200);
    expect(getValue(streamsStreamsDeleteResponse, "message"), 'delete message').toBe("stream deleted");

    // Execute Request
    let streamsGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(streamsGet1Response.statusCode, 'status code').toBe(200);
    expect(getValue(streamsGet1Response, "total"), 'total after delete').toBeGreaterThanOrEqual(0);
});

