// Generated by Skyramp v1.3.29 on 2026-06-26 16:32:58.098386133 +0000 UTC m=+446.872585033
// Command: skyramp generate integration rest \
// 		--auth-type Basic \
// 		--framework playwright \
// 		--language typescript \
// 		--output streams_ingest_delete_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/openobserve-testb/openobserve-testb/web/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/openobserve-testb/openobserve-testb/web/tests/scenario_streams-ingest-delete-lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Basic " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    let streamName = "skyramp_test_stream";

    // Request Body
    const JsonPostRequestBody = `[
            {
                "host": "localhost",
                "level": "info",
                "message": "skyramp test log entry"
            }
        ]`

    // Execute Request
    let jsonPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/{stream_name}/_json",
        method:"POST",
        body:JsonPostRequestBody,
        headers:headers,
        pathParams:{"stream_name": streamName}
    });

    // Generated Assertions
    expect(jsonPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(jsonPostResponse, "code"), 'code').toBe(200);
    expect(getValue(jsonPostResponse, "status.0.name"), 'ingest stream name').toBe(streamName);
    expect(getValue(jsonPostResponse, "status.0.failed"), 'ingest failed count').toBe(0);
    expect(getValue(jsonPostResponse, "status.0.successful"), 'ingest successful count').toBeGreaterThanOrEqual(1);

    // Execute Request
    let streamsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(streamsGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let streamsStreamsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams/{stream_name}",
        method:"DELETE",
        headers:headers,
        pathParams:{"stream_name": streamName}
    });

    // Generated Assertions
    expect(streamsStreamsDeleteResponse.statusCode, 'status code').toBe(204);

    // Execute Request
    let streamsGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/default/streams",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(streamsGet1Response.statusCode, 'status code').toBe(200);
});

